export const GET_USERS = 'home/GET_USERS';
export const GET_USERS_SUCCESS = 'home/GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'home/GET_USERS_ERROR';
export const TOGGLE_USERS_STATUS = 'home/TOGGLE_USERS_STATUS';

export const GET_FILTERED_USERS = 'home/GET_FILTERED_USERS';
export const GET_FILTERED_USERS_SUCCESS = 'home/GET_FILTERED_USERS_SUCCESS';
export const GET_FILTERED_USERS_ERROR = 'home/GET_FILTERED_USERS_ERROR';
export const TOGGLE_FILTERED_USERS_STATUS = 'home/TOGGLE_FILTERED_USERS_STATUS';

export const SET_API_OBJECT = 'home/SET_API_OBJECT';
